Make Terraformer access to IAM read-only
cisagov/cool-assessment-terraform pull request #142
Opened 2021-10-13 16:18 UTC by jsf9k

## 🗣 Description ##

This pull requests adds a statement to the Terraformer policy document that makes its IAM access read-only.

## 💭 Motivation and context ##

This stops the Terraformer instance from defeating the Terraformer policy by creating new users, policies, roles, etc.  I'm looking at you, @epicfaace!  :smiley:

## 🧪 Testing ##

I successfully applied these changes to env1 in our staging COOL environment.

## ✅ Checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - _eschew scope creep!_
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All new and existing tests pass.

2021-10-13 19:22 UTC, dav3r approved these changes
Makes sense to me! 🔒

2021-10-14 14:27 UTC, mcdonnnj requested changes
Makes sense. I had one request related to clarifying the documentation around the new policy statement.

2021-10-14 14:27 UTC, mcdonnnj commented on terraformer_policy.tf
> +  # arn:aws:iam::aws:policy/IAMReadOnlyAccess.
I think we should mention the rationale for not including the `iam:Generate*` permission from the built-in policy. An alternative would be to link to [this page in the AWS documentation](https://docs.aws.amazon.com/IAM/latest/UserGuide/reference_policies_examples_iam_read-only-console-no-reporting.html) since it matches the permissions we're allowing.

2021-10-14 21:37 UTC, jsf9k commented on terraformer_policy.tf
> +  # arn:aws:iam::aws:policy/IAMReadOnlyAccess.
I believe this outdated conversation can now be resolved.

2021-10-14 21:44 UTC, dav3r commented on terraformer_policy.tf
> +  # which will cover the IAM case.  We require IAM access to be
This comment now needs to be updated.

2021-10-14 21:47 UTC, dav3r approved these changes
Other than the comment change that I noted, this all looks good to me. 🦘

2021-10-14 21:48 UTC, jsf9k commented on terraformer_policy.tf
> +  # which will cover the IAM case.  We require IAM access to be
That policy gets attached [here](https://github.com/cisagov/cool-assessment-terraform/blob/93c422af1983953f184a70a7f2f5f5000747da87/terraformer_role.tf#L13-L19).  What needs to change?

2021-10-15 02:25 UTC, jsf9k commented on terraformer_policy.tf
> +  # which will cover the IAM case.  We require IAM access to be
Have a look at commit 041d892 and let me know if that scratches your itch.

2021-10-15 02:50 UTC, dav3r commented on terraformer_policy.tf
> +  # which will cover the IAM case.  We require IAM access to be
> That policy gets attached [here](https://github.com/cisagov/cool-assessment-terraform/blob/93c422af1983953f184a70a7f2f5f5000747da87/terraformer_role.tf#L13-L19). What needs to change?

Arg, I totally overlooked that- this is why I shouldn't review PRs at the end of the day.  Though the enhanced comments in https://github.com/cisagov/cool-assessment-terraform/commit/041d892a59aaa6bafa6a6b1fa0ccede95837f0b8 are lovely. 👍

2021-10-15 02:54 UTC, dav3r commented on terraformer_policy.tf
> +  # will give is read-only access to all IAM resources.  We require
Fix a couple of typos:
```suggestion
  # We will attach the arn:aws:iam::aws:policy/ReadOnlyAccess policy
  # to the same role to which the policy document will be attached, which
  # will give it read-only access to all IAM resources.  We require
```

2021-10-15 03:15 UTC, jsf9k commented on terraformer_policy.tf
> +  # which will cover the IAM case.  We require IAM access to be
No problem sir!

2021-10-15 20:44 UTC, mcdonnnj approved these changes
This makes sense. 🔒

2021-10-16 02:32 UTC, merged