Rename Assessor Portal to Assessor Workbench
cisagov/cool-assessment-terraform pull request #216
Opened 2023-04-19 15:44 UTC by jsf9k

## 🗣 Description ##

This pull request globally renames "Assessor Portal" to "Assessor Workbench".

## 💭 Motivation and context ##

It is necessary to do this now, since we recently updated Guacamole to use ED25519 SSH keys.  The old Assessor Portal AMI is no longer being created, and hence it cannot support the new SSH key type.  Therefore it is imperative to start using the new Assessor Workbench AMI now.

## 🧪 Testing ##

I used these changes to deploy an Assessor Workbench AMI to our staging COOL environment and verified that it functions as expected.

## ✅ Pre-approval checklist ##

- [x] This PR has an informative and human-readable title.
- [x] Changes are limited to a single goal - *eschew scope creep!*
- [x] All relevant type-of-change labels have been added.
- [x] I have read the [CONTRIBUTING](../blob/develop/CONTRIBUTING.md) document.
- [x] These code changes follow [cisagov code standards](https://github.com/cisagov/development-guide).
- [x] All relevant repo and/or project documentation has been updated to reflect the changes in this PR.
- [x] All new and existing tests pass.

2023-04-19 15:54 UTC, mcdonnnj requested changes

2023-04-19 15:54 UTC, mcdonnnj commented on README.md
> +| assessor\_portal\_security\_group | The security group for the Assessor Workbench instances. |
```suggestion
| assessor\_workbench\_instance\_profile | The instance profile for the Assessor Workbench instances. |
| assessor\_workbench\_instances | The Assessor Workbench instances. |
| assessor\_workbench\_security\_group | The security group for the Assessor Workbench instances. |
```

2023-04-19 15:54 UTC, mcdonnnj commented on assessorworkbench_ec2.tf
> +    Name = format("Assessorworkbench%d", count.index)
```suggestion
    Name = format("AssessorWorkbench%d", count.index)
```

2023-04-19 15:54 UTC, mcdonnnj commented on assessorworkbench_ec2.tf
> +    Name = format("Assessorworkbench%d", count.index)
```suggestion
    Name = format("AssessorWorkbench%d", count.index)
```

2023-04-19 15:54 UTC, mcdonnnj commented on outputs.tf
>  output "assessor_portal_instance_profile" {
```suggestion
output "assessor_workbench_instance_profile" {
```

2023-04-19 15:54 UTC, mcdonnnj commented on outputs.tf
>  output "assessor_portal_instances" {
```suggestion
output "assessor_workbench_instances" {
```

2023-04-19 15:54 UTC, mcdonnnj commented on outputs.tf
>  output "assessor_portal_security_group" {
```suggestion
output "assessor_workbench_security_group" {
```

2023-04-19 15:57 UTC, dav3r approved these changes
@mcdonnnj beat me to the punch on all the things.  Fix them and I'm 👍

2023-05-02 19:18 UTC, jasonodoom approved these changes

2023-05-17 08:23 UTC, mcdonnnj approved these changes
:shipit:

2023-05-19 03:01 UTC, merged