Enable permissions to modify the default route table for operations s…
cisagov/cool-assessment-terraform pull request #223
Opened 2023-08-25 15:14 UTC by FLeiXiuS

## 🗣 Description ##

VPC peering establishes a secure, private network connection by utilizing private IP addresses, connecting one or more Virtual Private Clouds (VPCs). To ensure the seamless peering of VPCs and the successful routing of data across the operations and private subnets, specific permissions need to be configured.

Here are the required permissions:

1. **Modify Default Operations Routing Table:** It's necessary to have the permission to make modifications to the default operations routing table. This adjustment involves adding routes for the newly peered networks. This step ensures that traffic can be correctly directed to the VPC networks that have been peered.
2. **Associate Operations Subnet with Operations Route Table:** It might seem logical that the default operations subnet should be automatically associated with the default operations route table. However, in the context of VPC peering, this association is not automatically assumed. Although AWS might consider this association as default behavior, it's insufficient for the requirements of VPC peering. Explicitly associating the operations subnet with a route table becomes vita in enabling routing to the peered networks.

## 💭 Context ##

Our infrastructure team frequently establishes redirectors and other services in external Virtual Private Clouds (VPCs) and various regions within AWS. Instead of directing our traffic through an Elastic IP (EIP) and the public internet IP space, our goal is to achieve internal routing of traffic using AWS infrastructure. This necessitates the implementation of VPC peering and ensuring that the appropriate permissions are in place for seamless and secure routing through private networks.

2023-08-25 15:26 UTC, jsf9k requested changes
I have a few minor changes to request.

I also have one comment.  If your VPC peering involves more than two VPCs then it usually makes more sense to use a Transit Gateway versus VPC peering.  This is because the Transit Gateway centralizes the rules that determine which VPCs can communicate, and you need only create `N` Transit Gateway Attachments versus `~N^2` VPC peering resources.  This advice may not apply in your use case, but I mention it just in case it's helpful.

2023-08-25 15:26 UTC, jsf9k commented on terraformer_permissionsboundary.tf
> +      aws_subnet.operations.arn
Alphabetize:
```suggestion
      aws_subnet.operations.arn,
      aws_subnet.private[var.private_subnet_cidr_blocks[0]].arn,
```

2023-08-25 15:26 UTC, jsf9k commented on terraformer_policy.tf
> +      aws_subnet.operations.arn
Alphabetization:
```suggestion
      aws_subnet.operations.arn,
      aws_subnet.private[var.private_subnet_cidr_blocks[0]].arn,
```

2023-08-25 15:54 UTC, dav3r commented
FYI, I worked with @FLeiXiuS on this during the testing stages.  Now we want to get more eyes and perspectives on this PR.

2023-08-25 17:56 UTC, FLeiXiuS commented
> I have a few minor changes to request.
> 
> I also have one comment. If your VPC peering involves more than two VPCs then it usually makes more sense to use a Transit Gateway versus VPC peering. This is because the Transit Gateway centralizes the rules that determine which VPCs can communicate, and you need only create `N` Transit Gateway Attachments versus `~N^2` VPC peering resources. This advice may not apply in your use case, but I mention it just in case it's helpful.

We don't necessarily need the VPC"s to route to each other in a star topology.  We're mostly interested in the operations VPC communicating with the external VPCs versus ALL of the VPCs being able to route to one another.  I suppose we could segment with SGs.  Curious to hear your thoughts.

2023-08-25 19:00 UTC, dav3r commented
> Explicitly associating the operations subnet with a route table becomes vital in enabling routing to the peered networks.

@jsf9k Can you think of any reasons why it would be a problem if we explicitly associated that default route table with the Operations subnet?  If we do that, then we wouldn't need to add the [permission to allow associating/disassociating route tables from the Operations subnet](https://github.com/FLeiXiuS/cool-assessment-terraform/blob/bb6bbaf101297fe3527b7b41d0b5eb64ec69b914/terraformer_policy.tf#L147), at least not for the use case @FLeiXiuS has expressed.

2023-08-28 14:53 UTC, dav3r commented
Since we already allow the Terraformer instance to disassociate the default routing table and associate a new one, I don't think there's any further risk from a security standpoint with allowing the Terraformer to modify routes in the default routing table.  @cisagov/team-ois (or anyone else) if you think otherwise, now is a great time to speak up.

2023-08-28 14:58 UTC, jsf9k commented
> > Explicitly associating the operations subnet with a route table becomes vital in enabling routing to the peered networks.
> 
> @jsf9k Can you think of any reasons why it would be a problem if we explicitly associated that default route table with the Operations subnet? If we do that, then we wouldn't need to add the [permission to allow associating/disassociating route tables from the Operations subnet](https://github.com/FLeiXiuS/cool-assessment-terraform/blob/bb6bbaf101297fe3527b7b41d0b5eb64ec69b914/terraformer_policy.tf#L147), at least not for the use case @FLeiXiuS has expressed.

I'd prefer that the default routing table be left alone, so we can point to it as an example if necessary.

2023-08-28 15:01 UTC, jsf9k commented
> Since we already allow the Terraformer instance to disassociate the default routing table and associate a new one, I don't think there's any further risk from a security standpoint with allowing the Terraformer to modify routes in the default routing table. @cisagov/team-ois (or anyone else) if you think otherwise, now is a great time to speak up.

If it were up to me then I'd prefer that the default routing table be left alone.  This is because new subnets not explicitly assigned a routing table will be assigned the default one.  I'd prefer that folks who want to modify the default routing table instead create a new one and explicitly associate it with the subnets they care about.

2023-08-28 15:19 UTC, dav3r commented
> > Since we already allow the Terraformer instance to disassociate the default routing table and associate a new one, I don't think there's any further risk from a security standpoint with allowing the Terraformer to modify routes in the default routing table. @cisagov/team-ois (or anyone else) if you think otherwise, now is a great time to speak up.
> 
> If it were up to me then I'd prefer that the default routing table be left alone. This is because new subnets not explicitly assigned a routing table will be assigned the default one. I'd prefer that folks who want to modify the default routing table instead create a new one and explicitly associate it with the subnets they care about.
> 
> That said, I can live with folks modifying the default routing table if there is a reason to prefer that approach.

@FLeiXiuS Can you please explain why you prefer to modify the default routing table rather than use a new routing table of your own creation?

2023-08-28 15:47 UTC, FLeiXiuS commented
> > > Since we already allow the Terraformer instance to disassociate the default routing table and associate a new one, I don't think there's any further risk from a security standpoint with allowing the Terraformer to modify routes in the default routing table. @cisagov/team-ois (or anyone else) if you think otherwise, now is a great time to speak up.
> > 
> > 
> > If it were up to me then I'd prefer that the default routing table be left alone. This is because new subnets not explicitly assigned a routing table will be assigned the default one. I'd prefer that folks who want to modify the default routing table instead create a new one and explicitly associate it with the subnets they care about.
> > That said, I can live with folks modifying the default routing table if there is a reason to prefer that approach.
> 
> @FLeiXiuS Can you please explain why you prefer to modify the default routing table rather than use a new routing table of your own creation?

Certainly.  I was unable to create another route table for the operations subnet and have that routeable without associating it to the subnet itself.  At that point, the default route table with the transit gateway and the IGW would not be apart of the route table.  

I could duplicate these routes in the new table, but at that point its the same effect to just modify the original route table.

2023-08-28 15:59 UTC, jsf9k approved these changes

2023-08-28 17:31 UTC, dav3r approved these changes
👍 👍

2023-08-30 14:56 UTC, jasonodoom approved these changes

2023-08-31 14:35 UTC, merged